# 数据预处理

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
col_names = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]
data10p = pd.read_csv('Data/kddcup.data_10_percent.gz', header=None, names = col_names)
data10p.describe()

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   

   wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
0               0       0    0   ...                      9   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate    label  
0                       0.0  normal.  

[1 rows x 42 columns]

In [16]:
data10p.head(2)

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   

   wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
0               0       0    0   ...                      9   
1               0       0    0   ...                     19   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate    label  
0                       0.0  normal.  
1                       0.0  normal.  

[2 rows x 42 columns]

In [61]:
dataset = data10p.iloc[:,:-1].values
dataset.shape

(494021, 41)

In [62]:
dataset[0:5,:]

array([[0, 'tcp', 'http', 'SF', 181, 5450, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 8, 8, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 9, 9,
        1.0, 0.0, 0.11, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 'tcp', 'http', 'SF', 239, 486, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 8, 8, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 19,
        19, 1.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 'tcp', 'http', 'SF', 235, 1337, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 8, 8, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 29,
        29, 1.0, 0.0, 0.03, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 'tcp', 'http', 'SF', 219, 1337, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 6, 6, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 39,
        39, 1.0, 0.0, 0.03, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 'tcp', 'http', 'SF', 217, 2032, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 6, 6, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 49,
        49, 1.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0]], dtype=object

### 虚拟编码

In [64]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
# 对第1到3列编码
dataset_encoded = dataset.copy()
print(dataset[0,1:4])
for i in range(1,4):
    dataset_encoded[:,i] = LabelEncoder().fit_transform(dataset_encoded[:,i])
    print(dataset_encoded[0,1:4])

['tcp' 'http' 'SF']
[1 'http' 'SF']
[1 22 'SF']
[1 22 9]


In [65]:
dataset_encoded[0,0:5]

array([0, 1, 22, 9, 181], dtype=object)

In [66]:
onehotencoder = OneHotEncoder(categorical_features=[1,2,3])
dataset_encoded = onehotencoder.fit_transform(dataset_encoded).toarray()

In [67]:
dataset_encoded.shape

(494021, 118)

### 特征缩放

In [69]:
from sklearn.preprocessing import StandardScaler
scer = StandardScaler()
dataset_scaled = scer.fit_transform(dataset_encoded)

In [70]:
dataset_scaled[0:3,:]

array([[-1.16094640e+00,  1.26460323e+00, -2.07294758e-01,
        -9.32997380e-03, -4.71876634e-03, -1.36477686e-02,
        -2.57755794e-02, -1.46496357e-02, -1.47872239e-02,
        -1.59723184e-02, -1.40137964e-02, -1.44407978e-02,
        -1.53252400e-02, -1.53252400e-02, -1.09592224e-01,
        -1.50586327e-02, -5.77479824e-02, -1.15042674e+00,
        -1.44407978e-02, -1.41575600e-02, -3.68518585e-02,
        -4.02234933e-02, -9.82266635e-02, -1.53911709e-02,
        -1.45107441e-02,  2.58532402e+00, -1.41575600e-02,
        -1.53911709e-02, -1.52590245e-02, -1.46496357e-02,
        -1.40858615e-02, -1.42998796e-02, -1.43705113e-02,
        -1.45107441e-02, -1.47185904e-02, -1.40858615e-02,
        -1.41575600e-02, -1.43705113e-02, -1.47185904e-02,
        -1.38685437e-02, -1.45803551e-02, -1.47872239e-02,
        -2.77450931e-02, -1.21930159e-01, -1.42274718e-03,
        -1.42998796e-02, -2.02251517e-02, -1.48555406e-02,
        -5.37997330e-01, -1.42274718e-03, -1.55872920e-0

### PCA降维

In [86]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
dataset_pca = pca.fit_transform(dataset_scaled)

In [87]:
print(pca.explained_variance_ratio_) 

[0.10877685 0.05035541]


In [88]:
dataset_pca[0,:]

array([1.00955079, 2.72177626])